### ISSUE TITLE
Remove outdated cheat sheets for respective versions or remove cheat sheets entirely?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-CheatSheets#1]
There is a list of cheat sheets: https://docs.typo3.org/m/typo3/docs-cheatsheets/main/en-us/CheatSheets.html

* first, decided if list of cheat sheets should be kept and will be maintained. (see next comment)
* If kept, should be checked for respective version if they are outdated and then removed.

todos:

* [x] remove link from  https://typo3.org/help/documentation
* [ ] officially decide if should be dropped
* [ ] remove (and add redirect?)

**Comment by sypets** [comment]
Do we still want to have this? Is this being maintained? Is it being linked to from start page?

**I suggest to remove the cheat sheets and the list of cheat sheets because:**


- it is community generated content which is difficult to assess, review and maintain - should we list any cheat sheet? Who decides if useful?
- there is lots of community generated content elsewhere which is not listed on docs.typo3.org
- it is not listed on start page anymore
- at least some of it is **outdated**, e.g. the "[New website cheat sheet](http://www.cheatography.com/achjaderleon/cheat-sheets/typo3-new-website/pdf/)" lists TypoScript options which are deprecated and removed since v9
- we removed other community generated content too (the snippets) for the same reasons
- more content to maintain then people actively doing the work. We have to be selective even if it hurts sometimes.
- also, the cheat sheets usually contain **no version information** (for which TYPO3 version). While some are universal - most will most likely depend on some piece of software and become outdated.
- currently not being actively maintained.
 
Some cheat sheets might be still up to date and useful but they could be made available elsewhere and can be found with a search engine 

I find cheat sheets in general very useful but I think they have to be actively maintained and up to date.

**Comment by sypets** [comment]
@oliverklee @xperseguers see :arrow_up:

**Comment by oliverklee** [comment]
I'd be fine with dropping this list.

**Comment by linawolf** [comment]
Repository is archived
